# Generated by Django 4.2.23 on 2025-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='updated_at',
            new_name='date_updated',
        ),
    ]
