# Generated by Django 4.2.23 on 2025-08-31 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareenquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softwareservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='softwareservice',
            name='estimated_timeline',
            field=models.CharField(default='default timeline', max_length=100),
        ),
        migrations.AlterField(
            model_name='softwareservice',
            name='service_type',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App Development'), ('desktop', 'Desktop Software'), ('api', 'API Development'), ('database', 'Database Design'), ('cloud', 'Cloud Services'), ('ai', 'AI/ML Solutions')], default='web', max_length=50),
        ),
    ]
