# Generated by Django 5.2.4 on 2025-08-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareenquiry',
            old_name='sumbitted_at',
            new_name='submitted_at',
        ),
    ]
