# Generated by Django 5.2.4 on 2025-08-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_services', '0002_rename_sumbitted_at_softwareenquiry_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareenquiry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
