# Generated by Django 4.2.24 on 2025-09-09 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphic_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_files',
            field=models.FileField(blank=True, null=True, upload_to='design_references/'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='image',
            field=models.ImageField(upload_to='designers/'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='speciality',
            field=models.CharField(choices=[('THUMBNAIL', 'Thumbnail'), ('WEB_DESIGN', 'Web Design'), ('BANNER', 'Banner'), ('LOGO', 'Logo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
