# Generated by Django 4.2.24 on 2025-09-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphic_design', '0002_designorder_remove_designer_image_and_more'),
        ('graphic_design', '0002_order_reference_files_alter_designer_image_and_more'),
    ]

    operations = [
    ]
