# Generated by Django 4.2.24 on 2025-09-14 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphic_design', '0005_designservice_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
