# Generated by Django 5.2.4 on 2025-08-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeautyServices',
            new_name='BeautyService',
        ),
    ]
