# Generated by Django 5.2.5 on 2025-08-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetology.beautyservice'),
        ),
        migrations.AlterField(
            model_name='stylistprofile',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetology.beautyservice'),
        ),
        migrations.DeleteModel(
            name='BeautyServices',
        ),
    ]
