# Generated by Django 4.2.23 on 2025-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0002_rename_beautyservices_beautyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beauty_images/'),
        ),
    ]
