# Generated by Django 5.2.4 on 2025-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0002_rename_beautyservices_beautyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyservice',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='beauty_services/'),
        ),
    ]
