# Generated by Django 4.2.23 on 2025-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetology", "0003_beautyservice_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
