# Generated by Django 4.2.23 on 2025-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetology", "0004_appointment_end_time_appointment_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="appointmentbooking",
            name="appointment_date",
            field=models.DateField(),
        ),
    ]
