# Generated by Django 4.2.23 on 2025-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Unknown Instructor', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
